/*
 * Copyright (c) 2017, ARM Limited and Contributors. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
#ifndef __HISI_PLATFORM_H__
#define __HISI_PLATFORM_H__

#include <hisi_crg.h>
#include <hisi_mem_map.h>

#define ASP_CFG_REG_BASE		0xE804E000

#define ASP_CFG_MMBUF_CTRL_REG		(ASP_CFG_REG_BASE + 0x148)

#define SCTRL_REG_BASE			0xFFF0A000

#define SCTRL_SCSYSSTAT_REG		(SCTRL_REG_BASE + 0x004)
#define SCTRL_DEEPSLEEPED_REG		(SCTRL_REG_BASE + 0x008)
#define SCTRL_SCISOEN_REG		(SCTRL_REG_BASE + 0x040)
#define SCTRL_SCISODIS_REG		(SCTRL_REG_BASE + 0x044)
#define SCTRL_SCPWREN_REG		(SCTRL_REG_BASE + 0x060)

#define SCTRL_SCPEREN0_REG		(SCTRL_REG_BASE + 0x160)
#define SCTRL_SCPERDIS0_REG		(SCTRL_REG_BASE + 0x164)
#define SCTRL_SCPERSTAT0_REG		(SCTRL_REG_BASE + 0x168)

#define SCTRL_SCPEREN1_REG		(SCTRL_REG_BASE + 0x170)
#define SCTRL_SCPERDIS1_REG		(SCTRL_REG_BASE + 0x174)
#define SCPEREN1_WAIT_DDR_SELFREFRESH_DONE_BYPASS	(1 << 31)

#define SCTRL_SCPEREN2_REG		(SCTRL_REG_BASE + 0x190)
#define SCTRL_SCPERDIS2_REG		(SCTRL_REG_BASE + 0x194)
#define SCTRL_SCPERSTAT2_REG		(SCTRL_REG_BASE + 0x198)
#define SCTRL_SCPEREN4_REG		(SCTRL_REG_BASE + 0x1B0)
#define GT_CLK_UFSIO_REF		(1 << 12)

#define SCTRL_SCPERDIS4_REG		(SCTRL_REG_BASE + 0x1B4)
#define SCTRL_SCPERRSTEN0_REG		(SCTRL_REG_BASE + 0x200)
#define SCTRL_SCPERRSTDIS0_REG		(SCTRL_REG_BASE + 0x204)
#define SCTRL_SCPERRSTSTAT0_REG		(SCTRL_REG_BASE + 0x208)
#define SCTRL_SCPERRSTEN1_REG		(SCTRL_REG_BASE + 0x20C)
#define SCTRL_SCPERRSTDIS1_REG		(SCTRL_REG_BASE + 0x210)
#define IP_RST_UFS_SUBSYS		(1 << 14)
#define SCTRL_SCPERRSTSTAT1_REG		(SCTRL_REG_BASE + 0x214)

#define SCTRL_SCPERRSTEN2_REG		(SCTRL_REG_BASE + 0x218)
#define SCTRL_SCPERRSTDIS2_REG		(SCTRL_REG_BASE + 0x21C)
#define SCTRL_SCPERRSTSTAT2_REG		(SCTRL_REG_BASE + 0x220)

#define SCTRL_SCCLKDIV2_REG		(SCTRL_REG_BASE + 0x258)
#define SCTRL_SCCLKDIV6_REG		(SCTRL_REG_BASE + 0x268)
#define SCTRL_SCCLKDIV9_REG		(SCTRL_REG_BASE + 0x274)

#define SCTRL_SCPERCTRL7_REG		(SCTRL_REG_BASE + 0x31C)
#define SCTRL_SCPERSTAT6_REG		(SCTRL_REG_BASE + 0x378)

#define SCTRL_SCINNERSTAT_REG		(SCTRL_REG_BASE + 0x3A0)
#define EMMC_UFS_SEL			(1 << 15)

#define SCTRL_BAK_DATA0_REG		(SCTRL_REG_BASE + 0x40C)
#define SCTRL_BAK_DATA4_REG		(SCTRL_REG_BASE + 0x41C)

#define SCTRL_SCPEREN0_SEC_REG		(SCTRL_REG_BASE + 0x900)
#define SCTRL_SCPERDIS0_SEC_REG		(SCTRL_REG_BASE + 0x904)

#define SCTRL_PERRSTEN1_SEC_REG		(SCTRL_REG_BASE + 0xA50)
#define SCTRL_PERRSTDIS1_SEC_REG	(SCTRL_REG_BASE + 0xA54)
#define SCTRL_PERRSTSTAT1_SEC_REG	(SCTRL_REG_BASE + 0xA58)
#define RST_ASP_SUBSYS_BIT		(1 << 0)

#define SCTRL_PERRSTEN2_SEC_REG		(SCTRL_REG_BASE + 0xB50)
#define SCTRL_PERRSTDIS2_SEC_REG	(SCTRL_REG_BASE + 0xB54)
#define SCTRL_PERRSTSTAT2_SEC_REG	(SCTRL_REG_BASE + 0xB58)

#define SCTRL_SCSOCID0_REG		(SCTRL_REG_BASE + 0xE00)

#define PMC_REG_BASE			0xFFF31000
#define PMC_PPLL1_CTRL0_REG		(PMC_REG_BASE + 0x038)
#define PMC_PPLL1_CTRL1_REG		(PMC_REG_BASE + 0x03C)
#define PMC_PPLL2_CTRL0_REG		(PMC_REG_BASE + 0x040)
#define PMC_PPLL2_CTRL1_REG		(PMC_REG_BASE + 0x044)
#define PMC_PPLL3_CTRL0_REG		(PMC_REG_BASE + 0x048)
#define PMC_PPLL3_CTRL1_REG		(PMC_REG_BASE + 0x04C)
#define PPLLx_LOCK			(1 << 26)
#define PPLLx_WITHOUT_CLK_GATE		(1 << 26)
#define PPLLx_CFG_VLD			(1 << 25)
#define PPLLx_INT_MOD			(1 << 24)
#define PPLLx_POSTDIV2_MASK		(0x7 << 23)
#define PPLLx_POSTDIV2(x)		(((x) & 0x7) << 23)
#define PPLLx_POSTDIV1_MASK		(0x7 << 20)
#define PPLLx_POSTDIV1(x)		(((x) & 0x7) << 20)
#define PPLLx_FRACDIV_MASK		(0x00FFFFFF)
#define PPLLx_FRACDIV(x)		((x) & 0x00FFFFFF)
#define PPLLx_FBDIV_MASK		(0xfff << 8)
#define PPLLx_FBDIV(x)			(((x) & 0xfff) << 8)
#define PPLLx_REFDIV_MASK		(0x3f << 2)
#define PPLLx_REFDIV(x)			(((x) & 0x3f) << 2)
#define PPLLx_BP			(1 << 1)
#define PPLLx_EN			(1 << 0)

#define PMC_NOC_POWER_IDLEREQ_REG	(PMC_REG_BASE + 0x380)
#define PMC_NOC_POWER_IDLEREQ_IVP	(1 << 14)
#define PMC_NOC_POWER_IDLEREQ_DSS	(1 << 13)
#define PMC_NOC_POWER_IDLEREQ_VENC	(1 << 11)
#define PMC_NOC_POWER_IDLEREQ_VDEC	(1 << 10)
#define PMC_NOC_POWER_IDLEREQ_ISP	(1 << 5)
#define PMC_NOC_POWER_IDLEREQ_VCODEC	(1 << 4)

#define PMC_NOC_POWER_IDLEACK_REG	(PMC_REG_BASE + 0x384)
#define PMC_NOC_POWER_IDLE_REG		(PMC_REG_BASE + 0x388)

#define DMAC_BASE			0xFDF30000
#define EDMAC_SEC_CTRL_REG		(DMAC_BASE + 0x694)
#define EDMAC_CX_AXI_CONF_REG(cn)	(DMAC_BASE + (0x834 + 0x40 * (cn)))

#define CCI400_REG_BASE			0xE8100000
#define CCI400_SL_IFACE3_CLUSTER_IX	0
#define CCI400_SL_IFACE4_CLUSTER_IX	1

#define GICD_REG_BASE			0xE82B1000
#define GICC_REG_BASE			0xE82B2000
/*
 * GIC400 interrupt handling related constants
 */
#define IRQ_SEC_PHY_TIMER		29
#define IRQ_SEC_SGI_0			8
#define IRQ_SEC_SGI_1			9
#define IRQ_SEC_SGI_2			10
#define IRQ_SEC_SGI_3			11
#define IRQ_SEC_SGI_4			12
#define IRQ_SEC_SGI_5			13
#define IRQ_SEC_SGI_6			14
#define IRQ_SEC_SGI_7			15
#define IRQ_SEC_SGI_8			16

#define IPC_REG_BASE			0xE896A000
#define IPC_BASE			(IPC_REG_BASE)

#define IOMG_REG_BASE			0xE896C000

#define IOCG_REG_BASE			0xE896C800

#define WDT0_REG_BASE			0xE8A06000
#define WDT1_REG_BASE			0xE8A07000
#define WDT_CONTROL_OFFSET		0x008
#define WDT_LOCK_OFFSET			0xC00

#define WDT_UNLOCK			0x1ACCE551
#define WDT_LOCKED			1

#define PCTRL_REG_BASE			0xE8A09000

#define USB3OTG_REG_BASE		0xFF100000

#define UFS_REG_BASE			0xFF3C0000

#define UFS_SYS_REG_BASE		0xFF3E0000

#define UFS_SYS_PSW_POWER_CTRL_REG	(UFS_SYS_REG_BASE + 0x004)
#define UFS_SYS_PHY_ISO_EN_REG		(UFS_SYS_REG_BASE + 0x008)
#define UFS_SYS_HC_LP_CTRL_REG		(UFS_SYS_REG_BASE + 0x00C)
#define UFS_SYS_PHY_CLK_CTRL_REG	(UFS_SYS_REG_BASE + 0x010)
#define UFS_SYS_PSW_CLK_CTRL_REG	(UFS_SYS_REG_BASE + 0x014)
#define UFS_SYS_CLOCK_GATE_BYPASS_REG	(UFS_SYS_REG_BASE + 0x018)
#define UFS_SYS_RESET_CTRL_EN_REG	(UFS_SYS_REG_BASE + 0x01C)
#define UFS_SYS_MONITOR_HH_REG		(UFS_SYS_REG_BASE + 0x03C)
#define UFS_SYS_UFS_SYSCTRL_REG		(UFS_SYS_REG_BASE + 0x05C)
#define UFS_SYS_UFS_DEVICE_RESET_CTRL_REG	(UFS_SYS_REG_BASE + 0x060)
#define UFS_SYS_UFS_APB_ADDR_MASK_REG	(UFS_SYS_REG_BASE + 0x064)
#define UFS_SYS_UFS_CRG_UFS_CFG_REG	(UFS_SYS_REG_BASE + 0x07C)

#define BIT_UFS_PSW_ISO_CTRL			(1 << 16)
#define BIT_UFS_PSW_MTCMOS_EN			(1 << 0)
#define BIT_UFS_REFCLK_ISO_EN			(1 << 16)
#define BIT_UFS_PHY_ISO_CTRL			(1 << 0)
#define BIT_SYSCTRL_LP_ISOL_EN			(1 << 16)
#define BIT_SYSCTRL_PWR_READY			(1 << 8)
#define BIT_SYSCTRL_REF_CLOCK_EN		(1 << 24)
#define MASK_SYSCTRL_REF_CLOCK_SEL		(3 << 8)
#define MASK_SYSCTRL_CFG_CLOCK_FREQ		(0xFF)
#define BIT_SYSCTRL_PSW_CLK_EN			(1 << 4)
#define MASK_UFS_CLK_GATE_BYPASS		(0x3F)
#define BIT_SYSCTRL_LP_RESET_N			(1 << 0)
#define BIT_UFS_REFCLK_SRC_SE1			(1 << 0)
#define MASK_UFS_SYSCTRL_BYPASS			(0x3F << 16)
#define MASK_UFS_DEVICE_RESET			(1 << 16)
#define BIT_UFS_DEVICE_RESET			(1 << 0)
#define MASK_UFS_MPHY_RHOLD			(0x1 << (11 + 16))
#define BIT_UFS_MPHY_RHOLD			(0x1 << 11)
#define MASK_IP_RST_UFS			(1<<16)
#define BIT_IP_RST_UFS			(1<<0)
#define MASK_IP_ARST_UFS			(1<<17)
#define BIT_IP_ARST_UFS			(1<<1)
#define EFUSE_RHOLD_BIT			(0x1 << 22)


#define IOMG_FIX_REG_BASE		0xFF3B6000

/* GPIO150: LED */
#define IOMG_FIX_006_REG		(IOMG_FIX_REG_BASE + 0x018)
/* GPIO151: LED */
#define IOMG_FIX_007_REG		(IOMG_FIX_REG_BASE + 0x01C)

#define IOMG_AO_REG_BASE		0xFFF11000

/* GPIO189: LED */
#define IOMG_AO_011_REG			(IOMG_AO_REG_BASE + 0x02C)
/* GPIO190: LED */
#define IOMG_AO_012_REG			(IOMG_AO_REG_BASE + 0x030)
/* GPIO202: type C enable. active low */
#define IOMG_AO_023_REG			(IOMG_AO_REG_BASE + 0x05C)
/* GPIO206: USB switch. active low */
#define IOMG_AO_026_REG			(IOMG_AO_REG_BASE + 0x068)
/* GPIO222: PCIE0 CLKREQ */
#define IOMG_AO_033_REG			(IOMG_AO_REG_BASE + 0x084)
/* GPIO219: PD interrupt. pull up */
#define IOMG_AO_039_REG			(IOMG_AO_REG_BASE + 0x09C)

#define IOCG_AO_REG_BASE		0xFFF1187C
/* GPIO219: PD interrupt. pull up */
#define IOCG_AO_043_REG			(IOCG_AO_REG_BASE + 0x030)

#define PL011_UART6_BASE		0xFFF32000


#define MEDIA1_CRG_REG_BASE         (0xE87FF000)
#define MEDIA1_CRG_PEREN0_REG	    (MEDIA1_CRG_REG_BASE + 0x000)
#define MEDIA1_CRG_PERDIS0_REG	    (MEDIA1_CRG_REG_BASE + 0x004)
#define MEDIA1_CRG_PEREN1_REG	    (MEDIA1_CRG_REG_BASE + 0x010)
#define MEDIA1_CRG_PERDIS1_REG	    (MEDIA1_CRG_REG_BASE + 0x014)
#define MEDIA1_CRG_PEREN2_REG	    (MEDIA1_CRG_REG_BASE + 0x020)
#define MEDIA1_CRG_PERDIS2_REG	    (MEDIA1_CRG_REG_BASE + 0x024)
#define MEDIA1_CRG_PERRSTEN0_REG	(MEDIA1_CRG_REG_BASE + 0x030)
#define MEDIA1_CRG_PERRSTDIS0_REG	(MEDIA1_CRG_REG_BASE + 0x034)
#define MEDIA1_CRG_PERRSTEN1_REG	(MEDIA1_CRG_REG_BASE + 0x03C)
#define MEDIA1_CRG_PERRSTDIS1_REG	(MEDIA1_CRG_REG_BASE + 0x040)
#define MEDIA1_CRG_CLKDIV0_REG	    (MEDIA1_CRG_REG_BASE + 0x060)
#define MEDIA1_CRG_CLKDIV2_REG	    (MEDIA1_CRG_REG_BASE + 0x068)
#define MEDIA1_CRG_CLKDIV5_REG	    (MEDIA1_CRG_REG_BASE + 0x074)
#define MEDIA1_CRG_CLKDIV9_REG	    (MEDIA1_CRG_REG_BASE + 0x084)
#define MEDIA1_PERI_AUTODIV0_REG	(MEDIA1_CRG_REG_BASE + 0x160)
#define MEDIA1_PERI_AUTODIV1_REG	(MEDIA1_CRG_REG_BASE + 0x164)
#define MEDIA1_PERI_AUTODIV4_REG	(MEDIA1_CRG_REG_BASE + 0x170)

#define MEDIA1_CRG_PERRSTEN_ISP_SEC_REG	    (MEDIA1_CRG_REG_BASE + 0x800)
#define MEDIA1_CRG_PERRSTDIS_ISP_SEC_REG	(MEDIA1_CRG_REG_BASE + 0x804)

#define MEDIA1_CRG_PERRSTEN_SEC_IVP_REG	    (MEDIA1_CRG_REG_BASE + 0x900)
#define MEDIA1_CRG_PERRSTDIS_SEC_IVP_REG	(MEDIA1_CRG_REG_BASE + 0x904)

#define MEDIA2_CRG_REG_BASE         (0xE8900000)

#define MEDIA2_CRG_PEREN0_REG	    (MEDIA2_CRG_REG_BASE + 0x000)
#define MEDIA2_CRG_PERDIS0_REG	    (MEDIA2_CRG_REG_BASE + 0x004)
#define MEDIA2_CRG_PERRSTEN0_REG	(MEDIA2_CRG_REG_BASE + 0x030)
#define MEDIA2_CRG_PERRSTDIS0_REG	(MEDIA2_CRG_REG_BASE + 0x034)

#define IVP32_CFG_BASE              (0xE8D80000)

#define VENC_CFG_BASE               (0xE8880000)

#define VDEC_CFG_BASE               (0xE8800000)

#endif  /* __HISI_H__ */
